Fix #250
callstack/react-native-pager-view pull request #251
Opened 2020-11-30 12:50 UTC by magicismight

# Summary

Fix #250.
This [method](https://github.com/callstack/react-native-viewpager/blob/master/ios/ReactNativePageView.m#L48-L55) seems unnecessary, had tested in orientation changing case, everything works fine without it.
But it will cause focus lose when subview layout changes.

## Test Plan

### What's required for testing (prerequisites)?

Check if ViewPager changes its layout after orientation changed.

### What are the steps to reproduce (after prerequisites)?

https://github.com/callstack/react-native-viewpager/issues/155

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅  |

## Checklist

- [X] I have tested this on a device and a simulator

2020-11-30 13:45 UTC, troZee commented
@krystiansliwa could you check it ?

2020-11-30 21:12 UTC, krystiansliwa commented
Hey, I tested that on example project and sometimes there is an issue with not filling whole container after rotation. @troZee It's known issue not related to that one?

2020-12-01 14:38 UTC, troZee commented
![Simulator Screen Shot - iPhone 11 - 2020-12-01 at 15 35 44](https://user-images.githubusercontent.com/12766071/100754135-f9213900-33ea-11eb-9d8b-470c247a188d.png)

Screen is wrong sized. There should not be a white space.

2020-12-01 14:38 UTC, troZee requested changes
Checkout the ss

2021-06-14 11:27 UTC, closed without merging