fix #312 - no initial page load on Android
callstack/react-native-pager-view pull request #322
Opened 2021-04-06 15:58 UTC by Lukas-Heiligenbrunner

# Summary

fix #312 with workaround solution from @KusStar (see https://github.com/callstack/react-native-pager-view/issues/312#issuecomment-807846238) 

## Checklist

- [X] I have tested this on a device and a simulator

2021-04-08 08:28 UTC, troZee requested changes

2021-04-08 08:28 UTC, troZee commented on src/PagerView.tsx
> +      // que action to next repaint cycle
please remove this comment

2021-04-08 08:44 UTC, troZee approved these changes

2021-04-08 08:45 UTC, merged

2021-04-08 09:16 UTC, Lukas-Heiligenbrunner commented on src/PagerView.tsx
> +      // que action to next repaint cycle
why? :D

2021-04-29 16:01 UTC, danilobuerger commented
@Lukas-Heiligenbrunner @troZee this doesn't really fix the issue. Now you can first see the first page before it skips to the `initialPage`.

2021-06-02 04:42 UTC, sajorahasan commented
Yes, I'm facing the same issue, I can see 0 index first before jumping to initialPage index.

2021-06-07 15:28 UTC, troZee commented
@danilobuerger @sajorahasan could you try this PR ? 

https://github.com/callstack/react-native-pager-view/pull/368

2021-06-14 10:11 UTC, rashidul0405 commented
> @Lukas-Heiligenbrunner @troZee this doesn't really fix the issue. Now you can first see the first page before it skips to the `initialPage`.

Same

2021-06-14 10:38 UTC, rashidul0405 commented
@troZee I just tested #368 and looks like the issue is fixed for android.

Step: `yarn remove react-native-pager-view && yarn add callstack/react-native-pager-view#368/head && ENVFILE=.env.development npx react-native run-android`