Lazy pager (js side)
callstack/react-native-pager-view pull request #326
Opened 2021-04-08 21:24 UTC by alpha0010

# Summary

## Test Plan

### What's required for testing (prerequisites)?

### What are the steps to reproduce (after prerequisites)?

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

2021-04-13 19:35 UTC, alpha0010 commented
@troZee These JS changes are ready for review.

2021-04-28 10:01 UTC, troZee requested changes
I have left few comments. Also I checked it on emulators and it works. 
Also I updated the next branch. Could you update your branch ?

I think, once you fix my comments, I will merge it.

2021-04-28 18:39 UTC, alpha0010 commented on src/LazyPagerView.tsx
> +type RenderWindowData = {
I do not think this is a good idea.  The majority of fields in `LazyPagerViewProps` are not relevant to `computeRenderWindow()` function.

2021-04-28 18:39 UTC, alpha0010 commented on src/LazyPagerView.tsx
> +  shouldComponentUpdate(
When wrapped as an animated component, events can trigger a very large number of irrelevant rerenders (even if inheriting from `PureComponent`).  This function improves performance by only rendering when changed props/state would have an actual effect on output.

2021-04-28 18:39 UTC, alpha0010 commented on src/PagerViewNative.tsx
> +type PagerViewNativeProps = {
Although they have some overlap in fields, `PagerViewNativeProps` has fields not relevant to `PagerViewProps` (e.g. `onMoveShouldSetResponderCapture`), and `PagerViewProps` has fields not relevant to `PagerViewNativeProps` (e.g. `keyboardDismissMode`).

This becomes especially important when adding the native Android/iOS code.  Properties `count` and `offset` will be required for the native view, but would be ignored if provided as props to the js view (but typescript would show errors if they are not provided).

2021-04-29 07:02 UTC, troZee commented on src/LazyPagerView.tsx
> +  shouldComponentUpdate(
Wooow 🤯  🥇

2021-04-29 07:05 UTC, merged

2021-06-10 12:54 UTC, troZee commented
https://github.com/callstack/react-native-pager-view/releases/tag/v6.0.0-rc.0