fix(Android): #303
callstack/react-native-pager-view pull request #423
Opened 2021-08-06 07:51 UTC by NiuGuohui

fix Issue (#303)

# Summary
See here: [https://github.com/android/views-widgets-samples/blob/master/ViewPager2/app/src/main/java/androidx/viewpager2/integration/testapp/NestedScrollableHost.kt](url)

I only tested example project. Looks okay.

## Test Plan

### What's required for testing (prerequisites)?

### What are the steps to reproduce (after prerequisites)?

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅    |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

2021-08-06 07:57 UTC, NiuGuohui commented
I also solved this in the Next branch.Do I need to open a new PR?

2021-08-09 13:58 UTC, troZee commented
> I also solved this in the Next branch.Do I need to open a new PR?

Hey @NiuGuohui. I would like to check this PR, before you make an additional PR to the `next` branch.

2021-08-10 02:03 UTC, NiuGuohui commented
> > I also solved this in the Next branch.Do I need to open a new PR?
> 
> Hey @NiuGuohui. I would like to check this PR, before you make an additional PR to the `next` branch.

ok

2021-08-10 11:35 UTC, troZee requested changes
Thank you @NiuGuohui for your investigation 🎉 
I have checked your changes and it works on my end. I added some comments to this PR. Fell free to start a discussion in case of any question.

2021-08-10 11:35 UTC, troZee commented on android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt
> +    val view = getViewPager(host)
please merge those two lines into one line for each react prop

2021-08-10 11:38 UTC, troZee commented
@NiuGuohui Could you add additional example, which refers to nested pager in this PR ? Thank you in advance

2021-08-11 07:20 UTC, NiuGuohui commented on android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt
> +  private fun getViewPager(view: NestedScrollableHost) = view.getChildAt(0) as ViewPager2
It doesn't meet expectations if `childAt(0)` return type is not ViewPager2.
```
private fun getViewPager(view: NestedScrollableHost): ViewPager2 {
    if(view.getChildAt(0) is ViewPager2) {
      return view.getChildAt(0) as ViewPager2
    } else {
      throw ClassNotFoundException("Could not retrieve ViewPager2 instance")
    }
}
```

2021-08-11 07:37 UTC, NiuGuohui commented on android/src/main/java/com/reactnativepagerview/PagerViewViewManager.kt
>      val vp = ViewPager2(reactContext)
yeah!

2021-08-11 08:43 UTC, NiuGuohui commented
> @NiuGuohui Could you add additional example, which refers to nested pager in this PR ? Thank you in advance

@troZee I added a nested example :)

2021-08-23 13:44 UTC, troZee commented on android/src/main/java/com/reactnativepagerview/NestedScrollableHost.kt
> +  private val parentViewPager: ViewPager2?
@NiuGuohui how about this ?

2021-09-01 16:57 UTC, nathansbird commented
@NiuGuohui This is super helpful, thanks! I can't seem to get it working on 0.63.3 (Latest version Expo supports). Any thoughts on why?

2021-09-07 02:20 UTC, NiuGuohui commented
> @NiuGuohui This is super helpful, thanks! I can't seem to get it working on 0.63.3 (Latest version Expo supports). Any thoughts on why?

I don’t know Expo well, can it run in a 0.63.3 independent project?

2021-09-13 11:44 UTC, troZee commented
> @NiuGuohui This is super helpful, thanks! I can't seem to get it working on 0.63.3 (Latest version Expo supports). Any thoughts on why?

Please check pager version in the expo SDK

2021-09-13 11:58 UTC, merged

2021-09-13 12:02 UTC, troZee commented
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.3