add docs for attaching onPageScroll handler with reanimated
callstack/react-native-pager-view pull request #491
Opened 2021-12-11 06:26 UTC by intergalacticspacehighway

# Summary

This PR adds a document section to integrate reanimated event handler with onPageScroll. Ideally it would be more convenient to export a hook `useAnimatedPageScrollHandler` but it'll add dependency on reanimated. I think creating a separate package for this hook can also be convenient!

## Test Plan
- I have [created a gist](https://gist.github.com/intergalacticspacehighway/52252474872c9e2246e398179920ccf2) which can be tested in RN example app which has reanimated installed and configured. The callback receives offset and position events. 
- Also this [repo](https://github.com/intergalacticspacehighway/pager-view-reanimated-repro) (App.js) includes the working example which can be referred.
- I am not really sure if there are any more cases.

### What's required for testing (prerequisites)?
- react-native-pager-view and react-native-reanimated

### What are the steps to reproduce (after prerequisites)?

- Run the [app](https://github.com/intergalacticspacehighway/pager-view-reanimated-repro) and try swiping pages. It should log the event or try updating values created using `useSharedValue`.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [x] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

Thanks for the great library 🙏

2022-01-03 10:43 UTC, troZee requested changes
Hey @intergalacticspacehighway 
Thank you for providing a doc improvements to the Pager. Could you add this snippet to the example folder ? It would be nice to have it inside the library example. 

Once you done it, I will merge it

2022-01-04 07:36 UTC, intergalacticspacehighway commented
@troZee Done. Tested the example on android and iOS.


https://user-images.githubusercontent.com/23293248/148024873-9e61f9eb-ad1d-4c53-96c9-b4c50c1cc711.mov

2022-01-04 07:39 UTC, intergalacticspacehighway commented on example/package.json
> +    "react-native-reanimated": "^2.3.1",
I don't think reanimated was being used in the example so this should not cause any issues!

2022-01-04 07:40 UTC, intergalacticspacehighway commented on example/android/app/src/main/java/com/example/reactnativepagerview/MainApplication.java
> +import com.swmansion.reanimated.ReanimatedJSIModulePackage; // <- add
These changes are from reanimated [installation steps](https://docs.swmansion.com/react-native-reanimated/docs/fundamentals/installation/)

2022-01-04 08:36 UTC, merged