fix(ios): incorrect pager height
callstack/react-native-pager-view pull request #580
Opened 2022-06-27 07:09 UTC by andreialecu

# Summary

#565 originally fixed this but #567 regressed it.

This should fix it again, more properly this time.

## Test Plan

- Open the "ScrollView inside PagerView Example" in an iOS simulator and rotate to landscape.
- Open the Keyboard Example and focus the text input, ensure the keyboard doesn't dismiss

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator

2022-06-27 07:12 UTC, andreialecu commented
This shows the test result on my end:

https://user-images.githubusercontent.com/697707/175880666-23754e72-37d5-4620-a511-fde524e55b19.mp4

https://user-images.githubusercontent.com/697707/175880765-af47cd45-d0ef-4a9e-a54e-e6729c7e194c.mp4


https://user-images.githubusercontent.com/697707/175880841-4f16cf13-b8f9-491c-892b-a203e710c23d.mp4

2022-06-29 07:40 UTC, troZee requested changes

2022-06-29 07:40 UTC, troZee commented on ios/ReactNativePageView.m
> -        // see:
Could you revert that comments too ? It will be much easier to have an information, why this workaround has been implemented

2022-07-05 18:25 UTC, troZee approved these changes

2022-07-05 18:25 UTC, merged

2022-07-05 18:32 UTC, troZee commented
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.25

2022-07-05 21:38 UTC, meenie commented
@[andreialecu](https://github.com/andreialecu), you are a hero!  I just upgraded to the newest version of React Navigation using Material Top Tabs yesterday and spent hours figuring out why the screen was blanked out when I opened up the keyboard.  I was about to downgrade and just saw this release. I confirmed, at least for me, that this fixed my issue. THANK YOU!!