Fix indicator animation on setPage
callstack/react-native-pager-view pull request #641
Opened 2022-11-09 22:16 UTC by krozniata

# Summary

This pull request fixes indicator animation issue on _setPage_ method call on **iOS**. 

When calling _setPage_ method to page which was more than 1 index away for current one, indicator wasn't smoothly animating to new index.

Pull request also fixes incorrect offset value issue, which was causing indicator to "jump" a bit on page change

Fixes #636 

## Test Plan

1. open paper/fabric example app
2. open `Basic Example`
3. navigate to last page by pressing `Last` on navigation panel
4. indicator should animate correctly

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [X] I have tested this on a device and a simulator

2022-11-15 13:50 UTC, troZee requested changes

2022-11-15 13:50 UTC, troZee commented on ios/Fabric/RNCPagerViewComponentView.mm
> +        _destinationIndex = 0;
```suggestion
        _destinationIndex = -1;
```
`-1` means that int is not initialized yet, assuming range from 0...n

2022-11-15 13:50 UTC, troZee commented on ios/Fabric/RNCPagerViewComponentView.mm
>          if (self.frame.size.height != 0) {
```suggestion
        if (scrollView.frame.size.height != 0) {
```

2022-11-15 13:50 UTC, troZee commented on ios/Fabric/RNCPagerViewComponentView.mm
>          if (self.frame.size.width != 0) {
```suggestion
        if (scrollView.frame.size.width != 0) {
```

2022-11-15 13:50 UTC, troZee commented on ios/ReactNativePageView.m
> -            offset = (point.x - self.frame.size.width)/self.frame.size.width;
Please apply all above comments to the paper arch

2022-11-16 11:21 UTC, merged

2022-11-22 05:03 UTC, Bardiamist commented
Nice!